"""create table for users

Revision ID: bb2f1dd2dad1
Revises: 
Create Date: 2023-07-11 18:33:23.223404

"""


# revision identifiers, used by Alembic.
revision = "bb2f1dd2dad1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
